export const milestones = [
  {
    time: new Date(-2700, 0, 1),
    color: "#FFA500",
    name: "The First Pyramid",
    country: "Egypt",
    short_description: "King Djoser’s Pyramid was built in the Nile Valley.",
    description: "I included this milestone for the reference.",
    image: "djoser_pyramid.jpg",
    link: "https://commons.wikimedia.org/wiki/File:Djoser_Pyramid_-_1900.jpg",
    link_text: "wikimedia",
    type: "structure"
  },
  {
    time: new Date(-7500, 0, 1),
    color: "#A580A5",
    name: "Chatal Huyuk",
    country: "Turkey",
    short_description: "Early neolithic settlement",
    description:
      "A really old settlement looks like a bundle of rectangular clay houses stacked on each other. Most 'houses' had roof entrances. People lived in high density, with animals, so it probably smelled awful. There was agriculture, livestock, social structure, and rituals.",
    image: "catalhoyuk.jpg",
    link: "https://imgur.com/gallery/atalh-y-k-is-city-founded-9-000-years-ago-its-considered-first-cirty-of-all-known-history-SyHgj9S",
    link_text: "imgur.com",
    type: "settlement",
  },
  {
    time: new Date(-5500, 0, 1),
    color: "#FFA500",
    name: "Toy Car",
    country: "Turkey, Mardin",
    short_description: "So cute—a toy car made of baked mud. Some child was very happy ten thousand years ago.",
    description: "",
    image: "mardin_toy_car.jpg",
    link: "",
    link_text: "",
    type: "artifact",
  },
  {
    time: new Date(-8000, 0, 1),
    color: "#FFA500",
    name: "Cave of Swimmers",
    country: "Egypt",
    short_description: "Cave art depicting swimming human figures.",
    description:
      "Ten thousand years ago someone painted swimming figures in the middle of what would become the Sahara desert. The place probably looked completely different back then.",
    image: "cave_of_swimmers.jpg",
    link: "https://en.wikipedia.org/wiki/Cave_of_Swimmers",
    link_text: "wikipedia",
    type: "art",
  },
  {
    time: new Date(-8000, 0, 1),
    color: "#A580A5",
    name: "Jericho",
    country: "Occupied Palestine",
    short_description: "The first walled city",
    description: "The place was populated for a long time, but by 8000 BC, they built a wall around it. They probably had a good reason for that.",
    image: "jericho.jpg",
    link: "https://www.thearchaeologist.org/blog/ancient-jericho-the-first-walled-city-in-history",
    link_text: "thearchaeologist.org",
    type: "settlement",
  },
  {
    time: new Date(-9700, 0, 1),
    color: "#A5A5FF",
    name: "Younger Dryas END",
    country: "",
    short_description: "From now on the climate in the Northern Hemisphere is heating up, leading to the interglacial period we are all living in now.",
    description: "",
    image: "",
    link: "",
    link_text: "",
    type: "milestone",
  },
  {
    time: new Date(-10900, 0, 1),
    color: "#A5A5FF",
    name: "Younger Dryas START",
    country: "",
    short_description: "The last ice age was coming to an end, and gradually the climate grew warmer. Then, a sudden cooling happened in the Northern Hemisphere. We are still not sure exactly why this occurred. One theory is that a large amount of cold water accumulated on a North American ice sheet suddenly dropped into the ocean and disrupted the currents.",
    description: "",
    image: "",
    link: "",
    link_text: "",
    type: "milestone",
  },
  {
    time: new Date(-10000, 0, 1),
    color: "#FFA500",
    name: "Tuc d'Audoubert Bisons",
    country: "Fance",
    short_description: "Amazing Paleolithic Bison Sculptures",
    description:
      "Yes, these bison are absolutely amazing. But besides the clay bison, there are fascinating child's fingerprints on a high cave shelf. The speculation is that a three-year-old was left there for some time simply because adults had to do something, and it was too dangerous to let the child wander around and fall. I like to think that this is a prehistoric version of parents putting a careless toddler on a bar stool.",
    image: "tuc_daudoubert_bison_sculptures.jpg",
    link: "https://www.sciencenews.org/article/modern-day-trackers-reinterpret-stone-age-cave-footprints",
    link_text: "sciencenews.org",
    type: "milestone",
  },
  {
    time: new Date(-11510, 0, 1),
    color: "#FFA500",
    name: "Red Deer Cave LL-1 Skull",
    country: "China",
    short_description: "A sapiens skull with strange features.",
    description: "Red Deer Cave people were a prehistoric population of modern humans. However their skull have strange features. They looked quite different from us.",
    image: "red_deer_cave_ll_1.jpg",
    link: "https://www.deviantart.com/philipedwin/art/Red-Deer-Cave-people-882382694",
    link_text: "Red deer cave people, by Philipe Dwin",
    type: "milestone",
  },
  {
    time: new Date(-11600, 0, 1),
    color: "#A580A5",
    name: "Göbekli Tepe",
    country: "Turkey",
    short_description: "Megalithic site built by hunter-gatherers.",
    description: "A megalithic site and settlement built by hunter-gatherers. This discovery broke the old consensus that settlements and megalithic structures could only be built by agricultural communities.",
    image: "gobekli_tepe.jpg",
    link: "",
    link_text: "",
    type: "milestone",
  },
  {
    time: new Date(-12900, 0, 1),
    color: "#FFA500",
    name: "The Sorcerer of Trois-Frères",
    country: "France",
    short_description: "The first depiction of an zoomorphic creature.",
    description:
      "In historic times, we know of many cultures with zoomorphic characters, for example, Creek myths and Egyptian gods. This is the first time we see a human-like body that combines features from various animals in prehistoric times.",
    image: "trois_freres_sorcerer.jpg",
    link: "https://en.wikipedia.org/wiki/The_Sorcerer_(cave_art)",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-14000, 0, 1),
    color: "#FFA500",
    name: "Altramira Bison",
    country: "Spain",
    short_description: "A beautiful bison cave art.",
    description:
      'They often call this the "Sistine Chapel of Prehistoric Art." Seriously, just check out the quality and technique -- different colors,, like, actual realistic proportions, and they totally understood animal shapes. There was one seriously skilled artist here fourteen thousand years ago!',
    image: "altamira_bison.jpg",
    link: "https://en.wikipedia.org/wiki/The_Sorcerer_(cave_art)",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-14500, 0, 1),
    color: "#FFA500",
    name: "Kapova Cave Camel",
    country: "Russia",
    short_description:
      "The Southern Urals aren't a desert now, and they weren't a desert before either. But someone painted a two-humped camel on the wall.",
    description: "",
    image: "kapova_camel.jpg",
    link: "https://en.wikipedia.org/wiki/Shulgan-Tash_Cave",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-15000, 0, 1),
    color: "#FFA500",
    name: "Grotte del la Marche Drawings",
    country: "France",
    short_description: "A cave with numerous prehistoric drawings.",
    description:
      "One of the drwaings depicts a man messing with another man, he is about to pour a water on the friend's head. To me this makes prehistoric people relateble and alive, they also had fun they also messed with their friends.",
    image: "grotte_de_la_marche_drawing.jpg",
    link: "",
    link_text: "",
    type: "milestone",
  },
  {
    time: new Date(-15000, 0, 1),
    color: "#FFA500",
    name: "Geissenklösterle Bone Flute",
    country: "Germany",
    short_description: "Oldest music instruments.",
    description:
      "Two flutes made out of swan bones and one ivory flute. I'd like to think they jammed in this cave!",
    image: "geissenklosterle_bone_flute.jpg",
    link: "https://en.wikipedia.org/wiki/Paleolithic_flute",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-17000, 0, 1),
    color: "#FFA500",
    name: "Lascaux Cave",
    country: "France",
    short_description:
      "A cave painting in Lascaux, near Montignac, France, depicting a bull and a horse.",
    description: "What I like about it is how artistic it is. Proportions are off, but notice how fluid and effortless the lines are. Quite a different vibe than the Altamira bison.",
    image: "lascaux_bull_horse.jpg",
    link: "https://www.britannica.com/place/Lascaux",
    link_text: "britannica",
    type: "milestone",
  },
  {
    time: new Date(-25000, 0, 1),
    color: "#FFA500",
    name: "La Pasiega",
    country: "Spain",
    short_description: "La Pasiega inscription",
    description: "Very old inscription-looking painting in a Spanish cave. Definitely not writing, but perhaps an attempt to encode a message?",
    image: "la_pasiega_inscription.jpg",
    link: "https://en.wikipedia.org/wiki/Cave_of_La_Pasiega",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-26000, 0, 1),
    color: "#FFA500",
    name: "Dolní Věstonice",
    country: "Czech Republic",
    short_description: "Bizzare burial of thee men aged from 16 to 25 years.",
    description:
      "The way the bodies are arranged in this burial is pretty unusual. The guy on the left had his hand stretched out over the middle person's pelvic area. Interestingly, both his hand and that area were covered in red ochre. Their heads were also covered in it. Then the guy on the right was impaled and buried face down. We don't know what happened here, but all these details really make you think about what could have gone on.",
    image: "dolni_vestonice.jpg",
    link: "https://en.wikipedia.org/wiki/Doln%C3%AD_V%C4%9Bstonice_(archaeological_site)",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-36000, 0, 1),
    color: "#FFA500",
    name: "Chauvet Cave",
    country: "France",
    short_description: "Drawings of lions hunting bison.",
    description: "Usually paleolithic caves depict bisons and hourses. But this one has sizable collection of rhino and many predatory animals, cave lions, leopards, bears, cave hyenas.",
    image: "chauvet_lions.jpg",
    link: "https://en.wikipedia.org/wiki/Chauvet_Cave",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-35000, 0, 1),
    color: "#FFA500",
    name: "Sungir",
    country: "Russia",
    short_description: "Exceptional Burial Site",
    description:
      "Two boys, 10 and 12 years old, were found in an extremely rich burial. Each had a spear made of straightened mammoth tusk (!) and clothing decorated with hundreds of beads. The 12-year-old had a protein-rich diet, while the younger boy obtained his protein from invertebrates. Beside him in the grave, a vessel made of femur bone was placed, covered in red ochre. This femur belonged to the child's grandfather, and this grandfather also had the same bizarre diet!",
    image: "sungir_children.jpg",
    link: "https://en.wikipedia.org/wiki/Sungir",
    link_text: "wikipedia",
    type: "milestone",
  },
  {
    time: new Date(-35000, 0, 1),
    color: "#FFA500",
    name: "Shanidar 1 Man",
    country: "Iraqi Kurdistan",
    short_description: "Exceptional elderly neanderthal man",
    description:
      "This man had a hard life. He lost his arm and he walked with a painful limp. Partially blind and deaf. Dispite being a cripple, he made it to his fourties. This  suggests that had community has been taking good care of him.",
    image: "shanidar_1.jpg",
    link: "https://www.worldhistory.org/image/5957/neanderthal-man/",
    link_text: "worldhistory.org",
    type: "milestone",
  },
  {
    time: new Date(-45000, 0, 1),
    color: "#FFA500",
    name: "Shanidar Flower Burial",
    country: "Iraqi Kurdistan",
    short_description: "An adult male, aged 30-45 years, was found with clumps of pollen, which is the best evidence we have for Neanderthal ritual burial.",
    description: "",
    image: "shanidar_flower_burial.jpg",
    link: "https://si-siris.blogspot.com/2019/06/discovering-culture-in-shanidar-cave.html",
    link_text: "si-siris.blogspot.com",
    type: "milestone",
  },
  {
    time: new Date(-74000, 0, 1),
    color: "#FFA500",
    name: "Toba Eruption.",
    country: "Indonesia, Sumatra",
    short_description: "The prehistoric super-volcano erruption.",
    description: "The Toba eruption covered Southeast Asia with ash. The volcanic material even reached Africa. This potentially caused a volcanic winter and impacted the climate for many years.",
    image: "toba_erruption.png",
    link: "https://www.researchgate.net/figure/Extent-of-the-Youngest-Toba-Tuff-YTT-eruption-with-respect-to-the-location-of-core_fig1_384331188",
    link_text: "Extent of the Youngest Toba Tuff",
    type: "milestone",
  },
  {
    time: new Date(-80000, 0, 1),
    color: "#FFA500",
    name: "Lady of Flores",
    country: "Indonesia",
    short_description: "Lady of Flores.",
    description:
      "A nearly complete 'hobbit' female skeleton of a human who lived about 80,000 years ago was found in Liang Bua cave on the island of Flores, Indonesia. This woman lived on an isolated island in an ecosystem with dwarf elephants and Komodo dragons, while Homo erectus, Homo sapiens, Neanderthals, and Denisovans were living on the big land.",
    image: "flores_lady.jpg",
    link: "https://www.deviantart.com/philipedwin/art/LB1-897964327",
    link_text: "Homo floresiensis, by Philip Edwin",
    type: "milestone",
  },
  {
    time: new Date(-100000, 0, 1),
    color: "",
    name: "Penghu 1",
    country: "Taiwan Strait",
    short_description: "Penghu 1",
    description:"",
    image: "",
    link: "",
    link_text: "",
    type: "milestone",
  },
];
